=== simhem1/XML-HA7/adressbuch.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="adressbuch">
        <xs:element name="eintrag" maxOccurs="unbounded">
            <xs:sequence>
                <xs:element name="vorname" type="xs:string"/>
                <xs:element name="nachname" type="xs:string"/>
<!--            <xs:element name="emailadresse" minOccurs="0" maxOccurs="unbounded">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value:"^.+@[^\.].*\.[a-z]{2,}$"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>-->
                <xs:element name="telefonnummer" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="geschlecht">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="male|female"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="geburtstag" type="xs:date"/>
                <xs:element name="id" type="xs:ID"/>
            </xs:sequence>
        </xs:element>
    </xs:element>
</xs:schema>

=== simhem1/XML-HA7/adressen.xml
<?xml version="1.0" encoding="UTF-8" ?>
<adressbuch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="adressbuch.xsd">
    <eintrag>
        <vorname>Captain</vorname>
        <nachname>Marvel</nachname>
        <telefonnummer>023442007</telefonnummer>
        <geschlecht>female</geschlecht>
        <geburtstag>15.05.1975</geburtstag>
        <id>108094123456</id>
    </eintrag>
    <eintrag>
        <vorname>Captain</vorname>
        <nachname>America</nachname>
        <!--<emailadresse>captain@america.com</emailadresse>-->
        <telefonnummer>02344711</telefonnummer>
        <telefonnummer>001911</telefonnummer>
        <geschlecht>male</geschlecht>
        <geburtstag>08.04.1965</geburtstag>
        <id>108084789123</id>
    </eintrag>
    <eintrag>
        <vorname>Iron</vorname>
        <nachname>Man</nachname>
        <!--<emailadresse>tony.stark@rub.de</emailadresse>-->
        <geschlecht>male</geschlecht>
        <geburtstag>17.10.1970</geburtstag>
        <id>108089414141</id>
    </eintrag>
    <eintrag>
        <vorname>Thor</vorname>
        <nachname>Odinson</nachname>
        <!--<emailadresse>info@w3l.de</emailadresse>-->
        <geschlecht>male</geschlecht>
        <geburtstag>11.12.1954</geburtstag>
        <id>108073333333</id>
    </eintrag>
    <eintrag>
        <vorname>Wonder</vorname>
        <nachname>Woman</nachname>
        <geschlecht>female</geschlecht>
        <geburtstag>02.01.1941</geburtstag>
        <id>108060333333</id>
    </eintrag>


</adressbuch>
